### ISSUE TITLE
Can't build j2se version: gradle-1.3 not available

### ISSUE THREAD

**Issue by delfer** [yandex-disk/yandex-disk-sdk-java#3]
```
➜  sdk-example git:(j2se) ./gradlew
Downloading http://services.gradle.org/distributions/gradle-1.3-bin.zip

Exception in thread "main" java.io.IOException: Server returned HTTP response code: 403 for URL: http://services.gradle.org/distributions/gradle-1.3-bin.zip
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1919)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:63)
	at org.gradle.wrapper.Download.download(Download.java:49)
	at org.gradle.wrapper.Install.createDist(Install.java:51)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
```

**Comment by yvoroshilov** [comment]
In gradle/wrapper/gradle-wrapper.properties change
`distributionUrl=http\://services.gradle.org/distributions/gradle-1.3-bin.zip`
to
`distributionUrl=https\://services.gradle.org/distributions/gradle-1.3-bin.zip`
